<?php

/**
 * @file
 * Webform prefill module.
 */

/**
 * Implements hook_libraries_info().
 */
function webform_prefill_libraries_info() {
  $libraries['jquery.formprefill'] = array(
    'name' => 'jQuery form prefill',
    'vendor url' => 'https://github.com/moreonion/jquery.formprefill',
    'download url' => 'https://github.com/moreonion/jquery.formprefill',
    'version arguments' => array(
      'file' => 'package.json',
      'pattern' => '/"version":\s*"(\d+.\d+.\d+)"/',
      'lines' => 5,
    ),
    'files' => array(
      'js' => array('jquery.formprefill.js'),
    ),
    'dependencies' => [
      'es6-promise',
    ],
  );

  $libraries['es6-promise'] = array(
    'name' => 'ES6-Promise',
    'vendor url' => 'https://github.com/stefanpenner/es6-promise',
    'download url' => 'https://github.com/stefanpenner/es6-promise',
    'version arguments' => array(
      'file' => 'package.json',
      'pattern' => '/"version":\s*"(\d+.\d+.\d+)"/',
      'lines' => 5,
    ),
    'files' => array(
      'js' => array(
        'dist/es6-promise.auto.min.js' => array(
          'preprocess' => FALSE,
        ),
      ),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_form_FORM_ID_alter() for webform_client_form().
 *
 * Add the prefill maping to the settings.
 */
function webform_prefill_form_webform_client_form_alter(&$form, &$form_state) {
  $js['type'] = 'setting';
  $js['data']['webform_prefill']['map'] = variable_get_value('webform_prefill_map');
  $js['data']['webform_prefill']['cookieDomain'] = variable_get_value('webform_prefill_cookie_domain');
  $js['data']['webform_prefill']['cookieMaxAge'] = variable_get_value('webform_prefill_cookie_max_age');
  $storage = variable_get_value('webform_prefill_storage');
  $js['data']['webform_prefill']['storage'] = is_array($storage) ? array_values($storage) : [$storage];
  $form['#attached']['js'][] = $js;

  $form['#attached']['libraries_load'][] = ['jquery.formprefill'];
}
