<?php

/**
 * @file
 * Webform prefill module.
 */

/**
 * Implements hook_libraries_info().
 */
function webform_prefill_libraries_info() {
  $libraries['jquery.formprefill'] = [
    'name' => 'jQuery form prefill',
    'vendor url' => 'https://github.com/moreonion/jquery.formprefill',
    'download url' => 'https://github.com/moreonion/jquery.formprefill',
    'version arguments' => [
      'file' => 'package.json',
      'pattern' => '/"version":\s*"(\d+.\d+.\d+)"/',
      'lines' => 5,
    ],
    'files' => [
      'js' => ['jquery.formprefill.js'],
    ],
    'dependencies' => [
      'es6-promise',
    ],
  ];

  $libraries['es6-promise'] = [
    'name' => 'ES6-Promise',
    'vendor url' => 'https://github.com/stefanpenner/es6-promise',
    'download url' => 'https://github.com/stefanpenner/es6-promise',
    'version arguments' => [
      'file' => 'package.json',
      'pattern' => '/"version":\s*"(\d+.\d+.\d+)"/',
      'lines' => 5,
    ],
    'files' => [
      'js' => [
        'dist/es6-promise.auto.min.js' => [
          'preprocess' => FALSE,
        ],
      ],
    ],
  ];

  return $libraries;
}

/**
 * Implements hook_page_build().
 *
 * We use hook_page_build() to load libraries as we only want them loaded for
 * HTML pages (not AJAX calls, private files, …).
 */
function webform_prefill_page_build(&$page) {
  $settings['map'] = variable_get_value('webform_prefill_map');
  $settings['cookieDomain'] = variable_get_value('webform_prefill_cookie_domain');
  $settings['cookieMaxAge'] = variable_get_value('webform_prefill_cookie_max_age');
  $storage = variable_get_value('webform_prefill_storage');
  $settings['storage'] = is_array($storage) ? array_values($storage) : [$storage];
  $settings['webform_prefill'] = $settings;
  drupal_add_js($settings, ['type' => 'setting']);

  libraries_load('jquery.formprefill');
}
